FROM --platform=amd64 rust:1.77.2-slim-bookworm AS build

WORKDIR /work

ARG TARGET=x86_64-unknown-linux-gnu

COPY ./ ./

RUN rustup target add ${TARGET}
RUN --mount=type=cache,target=/usr/local/cargo,from=rust:1.77.2,source=/usr/local/cargo \
    --mount=type=cache,target=./target/release \
        cargo build --release --target ${TARGET}

FROM gcr.io/distroless/cc-debian12:latest

WORKDIR /work

ARG EXE_FILENAME=voicepeak-aux
ARG TARGET=x86_64-unknown-linux-gnu

COPY --from=build /work/target/${TARGET}/release/${EXE_FILENAME} ./

ENTRYPOINT [ "./voicepeak-aux" ]
CMD [ "--help" ]
