FROM --platform=amd64 rust:1.77.2-slim-bookworm AS build

ARG TARGET=x86_64-apple-darwin

RUN rustup target add ${TARGET}
RUN cargo build -r --target ${TARGET}


FROM gcr.io/distroless/static-debian12:latest

WORKDIR /work

ARG EXE_FILENAME=voicepeak-aux.exe

COPY --from=build ./target/release/${EXE_FILENAME} ./

ENTRYPOINT [ "./${EXE_FILENAME}",  ]
CMD [ "--help" ]
